CREATE TABLE `dckz-web`.`main` (
  `id` INT NOT NULL,
  `surname` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `organization_name` VARCHAR(45) NULL,
  `bin` VARCHAR(45) NULL,
  `bin` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `file_ustav` INT NULL,
  `file_rekvis` INT NULL,
  `file_uch_doc` INT NULL,
  `prject_vmest` INT NULL,
  `specialization` VARCHAR(45) NULL,
  `start_time` INT NULL,
  `end_time` INT NULL,
  `language` VARCHAR(45) NULL,
  `form` VARCHAR(45) NULL,
  `groups` INT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdDate` DATETIME NULL,
  `lastModifiedBy` VARCHAR(45) NULL,
  `lastModifiedDate` DATETIME NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`)
);

